#!/usr/bin/env bash
#
# Install a released verda provider binary into a Terraform filesystem mirror.
#
# The provider is published as GitHub Release assets, not on the Terraform
# Registry, so Terraform has to be pointed at the binaries through its CLI
# config. This script downloads the release zip for the current platform,
# verifies it against the release SHA256SUMS, drops it into a mirror directory
# using Terraform's "packed" layout and writes a CLI config that routes
# `verda-cloud/verda` to that mirror. Works on a laptop and in GitHub Actions.
#
# Usage:
#   ./scripts/install-provider.sh [options]
#
# Options:
#   --version VER   Release to install, with or without the leading "v"
#                   (default: latest release of --repo)
#   --repo OWNER/R  GitHub repository that hosts the releases
#                   (default: $VERDA_PROVIDER_REPO or hrishin/terraform-provider-verda)
#   --mirror DIR    Mirror directory (default: $VERDA_PROVIDER_MIRROR or ~/.terraform.d/verda-mirror)
#   --all           Download every platform zip, not only the current one
#   --rc            Also write the config to ~/.terraformrc (overwrites it)
#
# After it runs, either export TF_CLI_CONFIG_FILE as printed, or use --rc.
# Under GitHub Actions the variable is appended to $GITHUB_ENV automatically.
#
# Then reference the provider as usual:
#   terraform {
#     required_providers {
#       verda = { source = "verda-cloud/verda", version = "1.1.4" }
#     }
#   }

set -euo pipefail

PROVIDER_ADDR="verda-cloud/verda"
PROVIDER_NAME="terraform-provider-verda"

REPO="${VERDA_PROVIDER_REPO:-hrishin/terraform-provider-verda}"
MIRROR="${VERDA_PROVIDER_MIRROR:-${HOME}/.terraform.d/verda-mirror}"
VERSION=""
ALL_PLATFORMS=false
WRITE_RC=false

while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --mirror) MIRROR="$2"; shift 2 ;;
    --all) ALL_PLATFORMS=true; shift ;;
    --rc) WRITE_RC=true; shift ;;
    -h|--help) sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [ -z "${VERSION}" ]; then
  VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)
  [ -n "${VERSION}" ] || { echo "Could not determine latest release of ${REPO}" >&2; exit 1; }
fi
VERSION="${VERSION#v}"

BASE_URL="https://github.com/${REPO}/releases/download/v${VERSION}"
MIRROR_DIR="${MIRROR}/registry.terraform.io/${PROVIDER_ADDR}"
mkdir -p "${MIRROR_DIR}"

if [ "${ALL_PLATFORMS}" = true ]; then
  PLATFORMS="darwin_amd64 darwin_arm64 linux_amd64 linux_arm64 windows_amd64"
else
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "${os}" in mingw*|msys*|cygwin*) os=windows ;; esac
  arch=$(uname -m)
  case "${arch}" in x86_64|amd64) arch=amd64 ;; aarch64|arm64) arch=arm64 ;; esac
  PLATFORMS="${os}_${arch}"
fi

SUMS="${PROVIDER_NAME}_${VERSION}_SHA256SUMS"
echo "Installing ${PROVIDER_ADDR} v${VERSION} from ${REPO} into ${MIRROR_DIR}"
curl -fsSL -o "${MIRROR_DIR}/${SUMS}" "${BASE_URL}/${SUMS}"

for platform in ${PLATFORMS}; do
  zip="${PROVIDER_NAME}_${VERSION}_${platform}.zip"
  echo "  ${zip}"
  curl -fsSL -o "${MIRROR_DIR}/${zip}" "${BASE_URL}/${zip}"
  expected=$(grep " ${zip}\$" "${MIRROR_DIR}/${SUMS}" | awk '{print $1}')
  [ -n "${expected}" ] || { echo "  ${zip} missing from ${SUMS}" >&2; exit 1; }
  if command -v sha256sum >/dev/null; then
    actual=$(sha256sum "${MIRROR_DIR}/${zip}" | awk '{print $1}')
  else
    actual=$(shasum -a 256 "${MIRROR_DIR}/${zip}" | awk '{print $1}')
  fi
  [ "${expected}" = "${actual}" ] || { echo "  checksum mismatch for ${zip}" >&2; exit 1; }
done
rm -f "${MIRROR_DIR}/${SUMS}"

RC_FILE="${MIRROR}/terraformrc"
cat > "${RC_FILE}" <<EOF
# Generated by scripts/install-provider.sh -- routes ${PROVIDER_ADDR} to the local mirror.
provider_installation {
  filesystem_mirror {
    path    = "${MIRROR}"
    include = ["${PROVIDER_ADDR}"]
  }
  direct {
    exclude = ["${PROVIDER_ADDR}"]
  }
}
EOF

if [ "${WRITE_RC}" = true ]; then
  cp "${RC_FILE}" "${HOME}/.terraformrc"
  echo "Wrote ${HOME}/.terraformrc"
fi

if [ -n "${GITHUB_ENV:-}" ]; then
  echo "TF_CLI_CONFIG_FILE=${RC_FILE}" >> "${GITHUB_ENV}"
  echo "Exported TF_CLI_CONFIG_FILE=${RC_FILE} to GITHUB_ENV"
else
  echo
  echo "Done. Point Terraform at the mirror with:"
  echo "  export TF_CLI_CONFIG_FILE=${RC_FILE}"
fi
